### ISSUE TITLE
How to use with AWS Glue?

### ISSUE THREAD

**Issue by kasunnirmala** [G-Research/spark-extension#103]
How to add the extension and the way to use it in AWS Glue? Either Notebook or shell script

**Comment by EnricoMi** [comment]
@leewalter78 do you have some suggestions, looks like you have used this with Glue.

**Comment by leewalter78** [comment]
https://github.com/G-Research/spark-extension/issues/64#issuecomment-1189400548

**Comment by kasunnirmala** [comment]
![image](https://user-images.githubusercontent.com/44490878/179823444-d9befa62-86d2-4267-95d4-b5b6a59ab57f.png)

I get an error something like this.

**Comment by EnricoMi** [comment]
You are using Python? Which `spark-extension` version did you use? Which Glue version?

Do you have step-by-step instructions for me to reconstruct this error on Glue?

**Comment by kasunnirmala** [comment]
> You are using Python? Which `spark-extension` version did you use? Which Glue version?
> 
> Do you have step-by-step instructions for me to reconstruct this error on Glue?

I was using `spark-extension_2.12:2.1.0-3.3` with Glue 3.0, and python 3

**Comment by EnricoMi** [comment]
Glue 3.0 uses Spark 3.1, so you should use `spark-extension_2.12:2.1.0-3.1`, not `...-3.3`.

**Comment by kasunnirmala** [comment]
> Glue 3.0 uses Spark 3.1, so you should use `spark-extension_2.12:2.1.0-3.1`, not `...-3.3`.

@EnricoMi Thanks. And you have inserted the s3 path of jar file for `Python library path` or `Dependent JARs path` ?

**Comment by EnricoMi** [comment]
> > Glue 3.0 uses Spark 3.1, so you should use `spark-extension_2.12:2.1.0-3.1`, not `...-3.3`.
> 
> @EnricoMi Thanks. And you have inserted the s3 path of jar file for `Python library path` or `Dependent JARs path` ?

As `Python library path`. I uploaded the `jar` file as is.
