### ISSUE TITLE
No matter what i do still "ModuleNotFoundError: No module named 'uk'"

### ISSUE THREAD

**Issue by Mimezzz** [G-Research/spark-extension#106]
Hi all,

I have tried multiple means to add the jar to my runtime, i am using pyspark 3.1.1.

I idownloaded the jar to my local and tried [Cyb3rWard0g](https://github.com/Cyb3rWard0g)'s approach here [(https://github.com/Cyb3rWard0g)](https://github.com/graphframes/graphframes/issues/104), it did not work.

I have also tried addjar or py-file, nothing changed. 

Can anyone please advise how can the package be found?

**Comment by EnricoMi** [comment]
What kind of Spark environment do you use?

**Comment by Mimezzz** [comment]
Hi @EnricoMi thanks for the reply, this is my local spark setting. I haven't installed other external packages before so no idea whether other would work for me.
![image](https://user-images.githubusercontent.com/78015770/184754615-1cbcfe85-9a58-4218-a228-a560b93a5d37.png)

just tried %%configure not working
![image](https://user-images.githubusercontent.com/78015770/184755723-17b554a1-12c8-4b2a-b611-58e10f39c1ab.png)

**Comment by EnricoMi** [comment]
Again, what environment do you use? Jupyter, Databricks? Which langauge, Python or Scala?

**Comment by Mimezzz** [comment]
it was run in local jupyter, i have used other ways to work around that, but if you can point out why the package can't be installed i am still planning to make an attempt

**Comment by EnricoMi** [comment]
It is as easy as setting Spark property `spark.jars.packages` to `uk.co.gresearch.spark:spark-extension_2.12:2.2.0-3.1` before the Spark session is started.

For me, the following Jupyter cells work:
```python
from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .config("spark.jars.packages", "uk.co.gresearch.spark:spark-extension_2.12:2.2.0-3.1") \
    .getOrCreate()
```
You can see from the output that it pulls the jar from Maven:
```
22/08/26 08:59:22 WARN Utils: Your hostname, pcs resolves to a loopback address: 127.0.1.1; using 192.168.179.111 instead (on interface wlp72s0)
22/08/26 08:59:22 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
:: loading settings :: url = jar:file:/home/enrico/Work/git/venv-3.8/lib/python3.8/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /home/enrico/.ivy2/cache
The jars for the packages stored in: /home/enrico/.ivy2/jars
uk.co.gresearch.spark#spark-extension_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-800fb258-bde3-40cd-9227-bbfc2f845ac9;1.0
	confs: [default]
	found uk.co.gresearch.spark#spark-extension_2.12;2.2.0-3.1 in central
downloading https://repo1.maven.org/maven2/uk/co/gresearch/spark/spark-extension_2.12/2.2.0-3.1/spark-extension_2.12-2.2.0-3.1.jar ...
	[SUCCESSFUL ] uk.co.gresearch.spark#spark-extension_2.12;2.2.0-3.1!spark-extension_2.12.jar (150ms)
:: resolution report :: resolve 5543ms :: artifacts dl 152ms
	:: modules in use:
	uk.co.gresearch.spark#spark-extension_2.12;2.2.0-3.1 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   1   |   1   |   0   ||   1   |   1   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-800fb258-bde3-40cd-9227-bbfc2f845ac9
	confs: [default]
	1 artifacts copied, 0 already retrieved (117kB/4ms)
```

```python
from gresearch.spark.diff import *

left = spark.createDataFrame([(1, "one"), (2, "two"), (3, "three")], ["id", "value"])
right = spark.createDataFrame([(1, "one"), (2, "Two"), (4, "four")], ["id", "value"])

left.diff(right, "id").show()
```
```
+----+---+----------+-----------+
|diff| id|left_value|right_value|
+----+---+----------+-----------+
|   N|  1|       one|        one|
|   C|  2|       two|        Two|
|   D|  3|     three|       null|
|   I|  4|      null|       four|
+----+---+----------+-----------+
```

**Comment by kijewskimateusz** [comment]
> Again, what environment do you use? Jupyter, Databricks? Which language, Python or Scala?

Hello @EnricoMi 
By any chance do you know how to proceed with installation of this package on Databricks Job cluster? Only place I've found that may allow me to install package is  below, but I don't know how to fill main class field

<img width="673" alt="image" src="https://user-images.githubusercontent.com/65126185/188328742-e12ac4b8-663f-4d16-8a32-95109fb8fb41.png">

**Comment by EnricoMi** [comment]
This is something else, this creates a task and its dependencies. What you want is add a dependency / library to a specific cluster. There, it does not ask for a main class.

**Comment by EnricoMi** [comment]
Looks like spark-extensions work fine with Jupyter notebooks, so closing this for now.
