### ISSUE TITLE
Python test-release.py isn't working

### ISSUE THREAD

**Issue by markmcwiggins** [G-Research/spark-extension#114]
Running python test-release.py gives:

```
file "./test-release.py", line 20, in <module>
    left.diff(right).show()
  File "/home/vn53el7/spark-extension/python/gresearch/spark/diff/__init__.py", line 518, in diff
    return Differ().diff(self, other, *id_columns)
  File "/home/vn53el7/spark-extension/python/gresearch/spark/diff/__init__.py", line 428, in diff
    jdiffer = self._to_java(jvm)
  File "/home/vn53el7/spark-extension/python/gresearch/spark/diff/__init__.py", line 361, in _to_java
    jdo = self._options._to_java(jvm)
  File "/home/vn53el7/spark-extension/python/gresearch/spark/diff/__init__.py", line 345, in _to_java
    self.diff_mode._to_java(jvm),
  File "/home/vn53el7/spark-extension/python/gresearch/spark/diff/__init__.py", line 34, in _to_java
    return jvm.uk.co.gresearch.spark.diff.DiffMode.withNameOption(self.name).get()
TypeError: 'JavaPackage' object is not callable

```

**Comment by EnricoMi** [comment]
Can you provide some more information on how you run the `test-release.py`?

**Comment by markmcwiggins** [comment]
python ./test-release.py

As simple as that ...

------- Original Message -------

**Comment by EnricoMi** [comment]
It is meant to be run through `test-release.sh`.

Files `test-release.scala` and `test-release.py` contain purre Spark code to test this package, while `test-release.sh` sets up the environment to performs these tests.

See [RELEASE.md](https://github.com/G-Research/spark-extension/blob/master/RELEASE.md).

**Comment by markmcwiggins** [comment]
The test-release.sh script isn't working either:

- the path for the download had hadoop3.3​ in it but I had to change it to just hadoop3​ and that worked to get past that point
- the https://oss.sonatype.org​ path is apparently wrong (looks like it changed recently too?) but that's as far as I've gotten.

Please fix the second problem so I can give this a try. Thanks

------- Original Message -------

**Comment by markmcwiggins** [comment]
I was just trying to get it to work at all​ and you said it required test-release.sh​ instead of just running test-release.py​ ...

The company is a Python shop and doesn't have Scala by default. I can download and fix the pom.xml if it can work with pyspark 2.4.8.

------- Original Message -------
