### ISSUE TITLE
the test-release.sh script is out of sync with repos from 2020

### ISSUE THREAD

**Issue by markmcwiggins** [G-Research/spark-extension#115]
./test-release.sh

Testing Spark         3.3.0 and Scala     2.13

--2022-10-10 08:45:43--  https://archive.apache.org/dist/spark/spark-
Resolving archive.apache.org (archive.apache.org)... 2a01:4f8:172:2ec5::2, 138.201.131.134
Connecting to archive.apache.org (archive.apache.org)|2a01:4f8:172:2ec5::2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-10 08:45:45 ERROR 404: Not Found.

The details: it's looking for a URL with this as part of it

                        hadoop="hadoop3.3-scala2.13"

But it is no longer "hadoop3.3" just "hadoop3".

I fixed that problem in my local copy and hit a further one:

./test-release.sh

Testing Spark 3.3.0 and Scala 2.13

--2022-10-10 15:53:46--  https://archive.apache.org/dist/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3-scala2.13.tgz
Resolving archive.apache.org (archive.apache.org)... 138.201.131.134, 2a01:4f8:172:2ec5::2
Connecting to archive.apache.org (archive.apache.org)|138.201.131.134|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 306344454 (292M) [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ 10% 10.8M 24s
 32768K ........ ........ ........ ........ 21% 9.68M 22s
 65536K ........ ........ ........ ........ 32% 11.4M 19s
 98304K ........ ........ ........ ........ 43% 15.5M 14s
131072K ........ ........ ........ ........ 54% 10.4M 12s
163840K ........ ........ ........ ........ 65% 7.43M 10s
196608K ........ ........ ........ ........ 76% 15.4M 6s
229376K ........ ........ ........ ........ 87% 18.0M 3s
262144K ........ ........ ........ ........ 98% 17.0M 0s
294912K ....                               100% 13.7M=25s

2022-10-10 15:54:11 (11.9 MB/s) - written to stdout [306344454/306344454]

https://oss.sonatype.org/content/groups/staging/ added as a remote repository with the name: repo-1
Ivy Default Cache set to: /home/vn53el7/.ivy2/cache
The jars for the packages stored in: /home/vn53el7/.ivy2/jars
:: loading settings :: url = jar:file:/usr/lib/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
uk.co.gresearch.spark#spark-extension_2.13 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-b8ef18c9-94e4-4b7e-94f6-3584326fca51;1.0
        confs: [default]
:: resolution report :: resolve 2352ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: uk.co.gresearch.spark#spark-extension_2.13;2.3.0-3.3-SNAPSHOT

Help please! This looks like an easy fix (for you) but it's keeping me from using your system! Thanks.

**Comment by EnricoMi** [comment]
Thanks for raising this issue, I am going to fix this in master in a moment.

As the name implies, `test-release.sh` is used for releasing this project.

What are you trying to do? How / for what do you want to use this project?

**Comment by markmcwiggins** [comment]
Through spark-submit.

------- Original Message -------

**Comment by EnricoMi** [comment]
Did you try

    spark-submit --packages uk.co.gresearch.spark:spark-extension_2.12:2.2.0-3.3 [script.py]

**Comment by markmcwiggins** [comment]
No I just tried test-release.sh so far. Did you push the update yet?

------- Original Message -------

**Comment by EnricoMi** [comment]
As I said: you do not need `test-release.sh` at all.

Please refer to https://github.com/G-Research/spark-extension#using-spark-extension.

**Comment by EnricoMi** [comment]
Looks like this has been solved in #117.
