### ISSUE TITLE
Add `gresearch.spark.parquet` to Python package in `setup.py`

### ISSUE THREAD

**Issue by ezhou7** [G-Research/spark-extension#192]
Hello there,

I am running into the trouble of reading user-defined file metadata from parquet files. Does this tool allow for reading metadata from multiple parquet files? I understand that the package `pyarrow` can read metadata, but would like something that can read and collect metadata from multiple parquet files into a dataframe for use.

Thanks!

**Comment by EnricoMi** [comment]
Thanks for reporting and fixing this in #191.

**Comment by ezhou7** [comment]
Thanks so much
