### ISSUE TITLE
Diff: Add floating point precision comparison

### ISSUE THREAD

**Issue by EnricoMi** [G-Research/spark-extension#2]
Comparing datasets containing floats or doubles can flag up false-positive changes due to floating point precision. Provide diff methods that compare floats and doubles with a given epsilon or precision.

**Comment by machielg** [comment]
It would be great to have this. Also to have a precision for any numerical field, in cases where small changes are not significant.

**Comment by EnricoMi** [comment]
@machielg what do you think about #127?
