### ISSUE TITLE
PySpark - Diff Epsilon Inclusive vs Exclusive

### ISSUE THREAD

**Issue by VinothKanna007** [G-Research/spark-extension#230]
# Pyspark

Is there anyway to mention `Inclusive <=` or `Exclusive <` for `DiffComparators.epsilon` in Pyspark ?

By Default what's the behaviour in pyspark ? Inclusive or Exclusive ?

```
options = DiffOptions() \
  .with_diff_column("diff") \
  .with_left_column_prefix("l") \
  .with_right_column_prefix("r") \
  .with_insert_diff_value("I") \
  .with_change_diff_value("Mismatch") \
  .with_delete_diff_value("D") \
  .with_nochange_diff_value("Match") \
  .with_change_column("changes") \
  .with_diff_mode(DiffMode.Default) \
  .with_data_type_comparator(DiffComparators.epsilon(sys.float_info.epsilon ** 0.5), DoubleType()) 
```

# Scala with Spark

I could see the [Methods](https://github.com/G-Research/spark-extension/blob/97ae911bfb8986ef2a401bcc755ac4e8b64e5f4e/DIFF.md?plain=1#L328) for scala. Do we have anything for Python ?

**Comment by EnricoMi** [comment]
The default is relative and inclusive.

All Scala methods also exist in Python, they just follow the usual Python naming scheme. So for `asRelative`, use `as_relative`. See
https://github.com/G-Research/spark-extension/blob/97ae911bfb8986ef2a401bcc755ac4e8b64e5f4e/python/gresearch/spark/diff/comparator/__init__.py#L67-L82

**Comment by VinothKanna007** [comment]
Thanks Man.

I need a small clarification here. please find the below:

Which 'option' I should go for 'double` data type ?

`Matching`  -> abs(x-y) <= sys.float_info.epsilon ** 0.5
`Mismatch` -> abs(x-y) > sys.float_info.epsilon ** 0.5

**Comment by EnricoMi** [comment]
I think `DiffComparators.epsilon(sys.float_info.epsilon ** 0.5).as_absolute()` should be exactly that.

**Comment by VinothKanna007** [comment]
Thank You!
