### ISSUE TITLE
Pyspark - Import Error

### ISSUE THREAD

**Issue by VinothKanna007** [G-Research/spark-extension#231]
# Error:
```
Invalid Syntax while running import
```

# FYI:

Spark Version:  `3.1.1-amzn-0`

Python Version - `3.6.10 | Anaconda, Inc.`

Jar: uk.co.gresearch.spark:spark-extension_`2.12:2.11.0-3.5"`

![IMG_20240128_162821](https://github.com/G-Research/spark-extension/assets/117466360/5da3bf48-e960-40e5-abb6-7f7497fdbe46)

**Comment by VinothKanna007** [comment]
Now i have switched to `different version of jar`

Now I'm getting an `Error` in `diff_with_options` Method. Attached the Full Stacktrace below


Spark Version:  `3.1.1-amzn-0`

Python Version - `3.6.10 | Anaconda, Inc.`

Jar: uk.co.gresearch.spark:spark-extension_`2.13:2.7.0-3.4"`

![IMG_20240128_170826](https://github.com/G-Research/spark-extension/assets/117466360/8fa8a748-7d1f-4c81-af98-97876678f516)

![IMG_20240128_170803](https://github.com/G-Research/spark-extension/assets/117466360/c4b0f338-fc6f-4ad3-a278-fa2839a2d230)

**Comment by EnricoMi** [comment]
The `invalid syntax` error reported in the description is due to using unsupported Python 3.6. Please use Python 3.7 or above.

The `NoClassDefFoundError` is due to using the Scala 2.13 version with PySpark, which uses Scala 2.12. Please use `spark-extension_2.12` instead.

**Comment by VinothKanna007** [comment]
Thanks! it works.

One more question: Is there any option to `ignore` the match value while displaying. Since im not bothered about Matching records

**Comment by EnricoMi** [comment]
Sure, use the sparse mode: https://github.com/G-Research/spark-extension/blob/master/DIFF.md#sparse-mode

**Comment by VinothKanna007** [comment]
Cool. Thanks @EnricoMi 

Btw this is a great package. Loved it♥️
