### ISSUE TITLE
Spark extension not working with 3.5.1

### ISSUE THREAD

**Issue by datanikkthegreek** [G-Research/spark-extension#232]
Hey all, can it be that the spark extension does not support spark 3.5.1. Once I updated I get below error message. Loading and saving parquet tables works as normal. On spark 3.5.0 it worked without any issue :)

Thanks already :)

![Screenshot_2024-03-06-20-04-22-506_com google android youtube](https://github.com/G-Research/spark-extension/assets/155961509/07d3ba34-ae54-4750-8466-d7ce185b03d2)

**Comment by EnricoMi** [comment]
Which spark-extension / pyspark-extension version are you using?

**Comment by datanikkthegreek** [comment]
Hi Enrico, thank you.

I didn't install the jar using pip install pyspark-extension==2.11.0.3.5. Seems when I upgrated to 3.5.1 something got messed up with the installation. I guess some conda issue. Everything works now :)
