### ISSUE TITLE
DiffOption withChangeColumn("changes") throws datatype mismatch error

### ISSUE THREAD

**Issue by SimiJo** [G-Research/spark-extension#24]
Scala version 2.11
maven : spark extension_2.11
             1.1.0-2.4

```
`val originalDF = Seq((1,"gaurav","jaipur",550,70000),(2,"sunil","noida",600,80000),(3,"rishi","ahmedabad",510,65000))
                .toDF("id","name","city","credit_score","credit_limit")
val changedDF= Seq((1,"gaurav","jaipur",550,70000),(2,"sunil","noida",650,90000),(4,"Joshua","cochin",612,85000))
                .toDF("id","name","city","credit_score","credit_limit")
val options = DiffOptions.default.withChangeColumn("changes") 
val diff = originalDF.diff(changedDF, options, "id")
diff.show(false)`
```

throws error,
```
Exception in thread main : org.spark.sql.analysisException : cannot resolve 'concat(CASE WHEN (`name`<=>`name`) THEN array() ELSE array(`name) END, CASE WHEN(`city` <=>`city`)..
due to datatype mismatch : input to function concat should have StringType or BinaryType but it's [array<string>, array<string>,array<string>, array<string>];;
```

**Comment by EnricoMi** [comment]
Thanks for raising this, looks like a 2.4 vs. 3.0 issue. I will have a look at it.

**Comment by EnricoMi** [comment]
Which Spark version are you using?

**Comment by SimiJo** [comment]
spark version : 2.3.0.cloudera3

**Comment by EnricoMi** [comment]
You are using spark extension_2.11-1.1.0-2.4, which targets Spark 2.4. The `withChangeColumn` option uses `concat` which obviously does not support arrays before 2.4. So I would argue 'withChangeColumn` is not supported before 2.4 either. You should consider upgrading to 2.4.

As of Sep, 2019, the 2.3 branch is not maintained anymore, and 2.3.0 is 2 1/2 years old. There have been so many bug fixes and performance improvements.

**Comment by SimiJo** [comment]
Many thanks.. It worked with 2.4 version.
Also, the Diffmode option seems to be really a cool feature but I am seeing error when used ".withDiffMode(DiffModes.Default)"

**Comment by EnricoMi** [comment]
Thanks for the feedback. Can you please raise another issue with the `DiffMode.Default` issue, so that I can reproduce it?
