### ISSUE TITLE
DiffModes.Default throws error value withDiffMode is not a member of uk.co.gresearch.spark.diff.DiffOptions

### ISSUE THREAD

**Issue by SimiJo** [G-Research/spark-extension#25]
scala - 2.11
spark - 2.4.0-cdh6.2.1
spark extension : 1.1.0-2.4

```
val options = DiffOptions.default
  .withDiffColumn("d")
  .withLeftColumnPrefix("l")
  .withRightColumnPrefix("r")
  .withInsertDiffValue("i")
  .withChangeDiffValue("c")
  .withDeleteDiffValue("d")
  .withNochangeDiffValue("n")
  .withChangeColumn("changes")
  .withDiffMode(DiffModes.Default)
  .withSparseMode(true)
```
showing compiler error,
`value withDiffMode is not a member of uk.co.gresearch.spark.diff.DiffOptions`
same issue with .withSparseMode"

**Comment by EnricoMi** [comment]
Those two options have not been released yet, they are only available on master. I will cut the v1.2 release tonight, then it will be available.

**Comment by EnricoMi** [comment]
I have just released v1.2.0, please give it a try.

**Comment by SimiJo** [comment]
yes it worked with the new version. Thanks!

**Comment by EnricoMi** [comment]
Excellent, thanks for getting back!
